from google.cloud import bigquery

project_id = "owen-project-337116"
bq_dataset = "user_bi_ds"
bq_table = "user_bi_table"
bq_view = "user_bi_view"

bq_schema = [
    bigquery.SchemaField("work_experiences", "RECORD", mode="REPEATED", fields=(bigquery.SchemaField("duration", "STRING"), bigquery.SchemaField("title", "STRING"))),
    bigquery.SchemaField("work_experience_list", "RECORD", mode="REPEATED", fields=(bigquery.SchemaField("duration", "STRING"), bigquery.SchemaField("title", "STRING"), bigquery.SchemaField("date", "STRING"), bigquery.SchemaField("location", "STRING"))),
    bigquery.SchemaField("computer_expertises", "STRING", mode="REPEATED"),
    bigquery.SchemaField("wanted_job_locations", "STRING", mode="REPEATED"),
    bigquery.SchemaField("wanted_job_types", "STRING", mode="REPEATED"),
    bigquery.SchemaField("wanted_job_titles", "STRING", mode="REPEATED"),
    bigquery.SchemaField("edu_department", "STRING"),
    bigquery.SchemaField("address", "STRING"),
    bigquery.SchemaField("edu_school", "STRING"),
    bigquery.SchemaField("edu_level", "STRING"),
    bigquery.SchemaField("id", "STRING"),
    bigquery.SchemaField("cell_phone", "STRING"),
    bigquery.SchemaField("gender", "STRING"),
    bigquery.SchemaField("age", "INTEGER"),
    bigquery.SchemaField("working_months", "STRING"),
    bigquery.SchemaField("email", "STRING"),
    bigquery.SchemaField("name", "STRING"),
    bigquery.SchemaField("languages", "RECORD", mode="REPEATED", fields=(bigquery.SchemaField("write", "STRING"), bigquery.SchemaField("read", "STRING"), bigquery.SchemaField("listen", "STRING"), bigquery.SchemaField("speak", "STRING"), bigquery.SchemaField("language", "STRING"))),
    bigquery.SchemaField("edu_status", "STRING"),
    bigquery.SchemaField("platform", "STRING")
    ]

bq_view_query =  f"""
    CREATE OR REPLACE VIEW `{project_id}.{bq_dataset}.{bq_view}`(
        id,
        name,
        age,
        gender,
        address,
        working_months,
        email,
        platform,
        edu_department,
        edu_school,
        edu_level,
        edu_status,
        cell_phone,
        work_experiences_titles,
        work_experiences_duration,
        language,
        listen,
        speak,
        read,
        write,
        work_experience_list_title,
        work_experience_list_duration,
        work_experience_list_location,
        work_experience_list_date,
        wanted_job_titles,
        wanted_job_types,
        wanted_job_locations,
        computer_expertises) AS
    SELECT
    id,
    name,
    age,
    gender,
    address,
    working_months,
    email,
    platform,
    edu_department,
    edu_school,
    edu_level,
    edu_status,
    cell_phone,
    ARRAY_AGG(title) AS work_experiences_titles,
    ARRAY_AGG(duration) AS work_experiences_duration,
    ARRAY_AGG(language) AS language,
    ARRAY_AGG(listen) AS listen,
    ARRAY_AGG(speak) AS speak,
    ARRAY_AGG(read) AS read,
    ARRAY_AGG(write) AS write,
    ARRAY_AGG(work_experience_list_title) AS work_experience_list_title,
    ARRAY_AGG(work_experience_list_duration) AS work_experience_list_duration,
    ARRAY_AGG(work_experience_list_location) AS work_experience_list_location,
    ARRAY_AGG(work_experience_list_date) AS work_experience_list_date,
    ARRAY_AGG(wanted_job_titles) AS wanted_job_titles,
    ARRAY_AGG(wanted_job_types) AS wanted_job_types,
    ARRAY_AGG(wanted_job_locations) AS wanted_job_locations,
    ARRAY_AGG(computer_expertises) AS computer_expertises,
    FROM (
        SELECT
            DISTINCT id,
            name,
            age,
            gender,
            address,
            working_months,
            email,
            platform,
            edu_department,
            edu_school,
            edu_level,
            edu_status,
            cell_phone,
            work_experience.title,
            work_experience.duration,
            languages.language,
            languages.listen,
            languages.speak,
            languages.read,
            languages.write,
            work_experience_list.title AS work_experience_list_title,
            work_experience_list.duration AS work_experience_list_duration,
            work_experience_list.location AS work_experience_list_location,
            work_experience_list.date AS work_experience_list_date,
            wanted_job_titles,
            wanted_job_types,
            wanted_job_locations,
            computer_expertises
        FROM
            `{project_id}.{bq_dataset}.{bq_table}`,
            UNNEST(work_experiences) AS work_experience,
            UNNEST(work_experience_list) AS work_experience_list,
            UNNEST(languages) AS languages,
            UNNEST(wanted_job_titles) AS wanted_job_titles,
            UNNEST(wanted_job_types) AS wanted_job_types,
            UNNEST(wanted_job_locations) AS wanted_job_locations,
            UNNEST(computer_expertises) AS computer_expertises)
        GROUP BY
            id,
            name,
            age,
            gender,
            address,
            working_months,
            email,
            platform,
            edu_department,
            edu_school,
            edu_level,
            edu_status,
            cell_phone;
    """